# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-SCRIPT
  sudo apt update && apt upgrade
  sudo apt install -y \
    bash \
    p7zip-full \
    wget \
    xorriso \
    squashfs-tools

  cp -R /vagrant /workdir
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_version = "20231011.0.0"

  config.vm.synced_folder '.', '/vagrant'

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false

    vb.cpus = "8"
    vb.memory = "4096"
  end

  config.vm.provision "shell", inline: $script
end
